config/routes.rb
Rails.application.routes.draw do
  resources :musics

root to: 'users#index'
devise_for :users
 resources :users do 
  collection do 
    get 'sign_in'
    get 'sign_up'
    post 'valid_user'
  end
end
resources :contacts,:only => [:new,:create,:index]
match "/contacts/", :controller => 'contacts',:action => 'index' , :via => [:get, :post]
resources :courses ,:only => [:index,:new,:create,:show,:edit,:update,:destroy]
resources :gadgets,:except => :delete
resources :users_admin do
  collection do
    get 'sign_out'
    end
  end
end 

app/models/analysis_group.rb
class AnalysisGroup < ActiveRecord::Base
  has_and_belongs_to_many :gadgets
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/contacts.rb
class Contacts < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
  # has_and_belongs_to_many :gadgets
end

app/models/currencies.rb
class Currencies < ActiveRecord::Base
  has_one :gadgets
end

app/models/currency.rb
class Currency < ActiveRecord::Base

 has_one :gadgets

end

app/models/gadget.rb
class Gadget < ActiveRecord::Base
  has_and_belongs_to_many :analysis_groups 
  has_and_belongs_to_many :type_of_methods
  belongs_to :currencys
  has_and_belongs_to_many :qualify_area_of_interests
end
# class Currency < ActiveRecord::Base
#   has_one :gadgets
# end

app/models/gadgets_qua_area_ints.rb
class GadgetsQuaAreaInts < ActiveRecord::Base
end

app/models/idea.rb
class Idea < ActiveRecord::Base
mount_uploader :picture, PictureUploader
end

app/models/music.rb
class Music < ActiveRecord::Base
has_attached_file :image, :styles => {:small => "100*100"}
validates_attachment_presence :image
validates_attachment_content_type :image, :content_type => [ 'image/png','image/jpeg','image/jpeg']
has_attached_file :document
validates_attachment_presence :document
validates_attachment_content_type :document, :content_type => [ 'application/pdf','text/plain']
has_attached_file :audio
validates_attachment_presence :audio
validates_attachment_content_type :audio, :content_type => [ 'audio/mp3','audio/mpeg']
end

app/models/type_of_method.rb
class TypeOfMethod < ActiveRecord::Base
  has_and_belongs_to_many :gadgets
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email,:password, presence: true
  def _user
    @_user = current_user.email
  end
end

app/controllers/users_admin_controller.rb
class UsersAdminController < ApplicationController
  def index
    @users = User.all
  end
  def show
    @user = User.find(params[:id])
  end
  def create
    @user = User.new
    @user.first_name = params[:user][:first_name]
    @user.last_name = params[:user][:last_name]
    @user.institution = params[:user][:institution]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    if @user.save
      redirect_to users_admin_index_path
    else
      render 'new'
    end
  end
  def new
    @user= User.new
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    @user.first_name = params[:user][:first_name]
    @user.last_name = params[:user][:last_name]
    @user.institution = params[:user][:institution]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.role = params[:user][:role]
    if @user.save
      redirect_to users_admin_index_path
    else
      render 'edit'
      #flash[:notice] = "You are signed up successfully"
    end
  end
  def destroy
      User.find(params[:id]).destroy
      redirect_to users_admin_index_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @list = User.all
  end
  def create
    @user = User.new
    @user.first_name = params[:user][:first_name]
    @user.last_name = params[:user][:last_name]
    @user.institution = params[:user][:institution]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    if
      @user.save
      redirect_to users_admin_index_path
      flash[:notice] = "You are signed up successfully"
    end
  end
  # def show
  #   @user = User.find(params[:id])
    
  # end
  def new
     render sign_up_users_path
  end
  def update
  end
  def valid_user
    @temp_email = params[:user][:email]
    @temp_password = params[:user][:password]
    @check_email = User.find_by_email(@temp_email)
    @check_password = User.find_by_password(@temp_password)
    if @check_email.nil? or @check_password.nil?
      flash[:notice] = "Entered Email-Id/Password is Invalid"
      redirect_to sign_in_users_path
    else
      redirect_to users_admin_index_path
    end
  end
  def sign_in
  end
  def sign_up
  end
  def sign_out
     @user.email = nil
     @user.password = nil
     render :text => params.inspect and return 
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/gadgets_helper.rb
module GadgetsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/usres_helper.rb
module UsresHelper
end

app/views/users_admin/_form.html.erb
    <legend>
      <h4>To get access to this inventory list of gadgets please fill out the following form. Thank you </h4>
    </legend>
        
    <div class="form-group row">
      <%= user.label :first_name, class: "string optional control-label control-label col-md-2 col-lg-2" %>
        <div class="col-md-4 col-lg-4">
              <%= user.text_field :first_name, class: "form-control" %>
        </div>
    </div>

    <div class="form-group row">
          <%= user.label :last_name, class: "string optional control-label control-label col-md-2 col-lg-2" %>
            <div class="col-md-4 col-lg-4">
          <%= user.text_field :last_name, class: "form-control" %>
            </div>
    </div>

    <div class="form-group row">
          <%= user.label :Institution, class: "string optional control-label control-label col-md-2 col-lg-2" %>
            <div class="col-md-4 col-lg-4">
          <%= user.text_field :institution, class: "form-control" %>
            </div>
    </div>

    <div class="form-group row">
          <%= user.label :Email, class: "string optional control-label control-label col-md-2 col-lg-2" %>
            <div class="col-md-4 col-lg-4">
          <%= user.text_field :email, class: "form-control" %>
            </div>
    </div>
        
    <div class="form-group row">
          <%= user.label :Password, class: "string optional control-label control-label col-md-2 col-lg-2" %>
            <div class="col-md-4 col-lg-4">
          <%= user.password_field :password, class: "form-control" %>
            </div>
    </div>

    <div class="form-group row">
          <%= user.label :Confirmation, class: "string optional control-label control-label col-md-2 col-lg-2" %>
            <div class="col-md-4 col-lg-4">
          <%= user.password_field :confirmation, class: "form-control" %>
            </div>
    </div>

    
   

    

app/views/users_admin/_form.html.haml
%legend
  %h4 To get access to this inventory list of gadgets please fill out the following form. Thank you
.form-group.row
  = user.label :first_name, class: "string optional control-label control-label col-md-2 col-lg-2"
  .col-md-4.col-lg-4
    = user.text_field :first_name, class: "form-control"
.form-group.row
  = user.label :last_name, class: "string optional control-label control-label col-md-2 col-lg-2"
  .col-md-4.col-lg-4
    = user.text_field :last_name, class: "form-control"
.form-group.row
  = user.label :Institution, class: "string optional control-label control-label col-md-2 col-lg-2"
  .col-md-4.col-lg-4
    = user.text_field :institution, class: "form-control"
.form-group.row
  = user.label :Email, class: "string optional control-label control-label col-md-2 col-lg-2"
  .col-md-4.col-lg-4
    = user.text_field :email, class: "form-control"
.form-group.row
  = user.label :Password, class: "string optional control-label control-label col-md-2 col-lg-2"
  .col-md-4.col-lg-4
    = user.password_field :password, class: "form-control"
.form-group.row
  = user.label :Confirmation, class: "string optional control-label control-label col-md-2 col-lg-2"
  .col-md-4.col-lg-4
    = user.password_field :confirmation, class: "form-control"
    

app/views/users_admin/contact.html.erb
  <div class="container-fluid">
    <div class="row">

        <div class="col-md-10">
            <div class="row">
  <div class="col-md-9">
    <div class="well">
  <div class="row well form-style">
    <h4>If you want to contact us please fill out the form below we get back to you as soon as possible. </h4>
    <h4>Thank you</h4>
  <div class="col-md-6">
   
  <div style="margin:0;padding:0;display:inline">
      <input name="utf8" type="hidden" value="&#x2713;" />
      <input name="authenticity_token" type="hidden" value="FVVqASyLBGLnMLPiJoYTVOgcdust65tXz++bKPDsWYo=" />
    </div>
                           
    <label class="string required control-label" for="contact_name"><abbr title="required">*</abbr> Name</label>
    <input class="form-control" id="name" name="contact[name]" size="61" type="text" />
                    
    <label class="email required control-label" for="contact_email"><abbr title="required">*</abbr> Email</label>
    <input class="form-control" id="email" name="contact[email]" required="required" size="61" type="email" value="" />
                            
    <label class="text required control-label" for="contact_message"><abbr title="required">*</abbr> Message</label>
    <textarea class="form-control" cols="40" id="text" name="contact[message]" rows="10" type="text">
    </textarea>
                              
    <input class="btn btn-primary btn-style " name="commit" type="submit" value="Send" />
    <button class="btn btn-default btn-style"><a href="/">Cancel</a></button>
  </form>  
</div>
</div>
</body>
</html>

app/views/users_admin/contact.html.haml
.container-fluid
  .row
    .col-md-10
      .row
        .col-md-9
          .well
            .row.well.form-style
              %h4 If you want to contact us please fill out the form below we get back to you as soon as possible.
              %h4 Thank you
              .col-md-6
                %div{:style => "margin:0;padding:0;display:inline"}
                  %input{:name => "utf8", :type => "hidden", :value => "✓"}/
                  %input{:name => "authenticity_token", :type => "hidden", :value => "FVVqASyLBGLnMLPiJoYTVOgcdust65tXz++bKPDsWYo="}/
                %label.string.required.control-label{:for => "contact_name"}
                  %abbr{:title => "required"} *
                  Name
                %input#name.form-control{:name => "contact[name]", :size => "61", :type => "text"}/
                %label.email.required.control-label{:for => "contact_email"}
                  %abbr{:title => "required"} *
                  Email
                %input#email.form-control{:name => "contact[email]", :required => "required", :size => "61", :type => "email", :value => ""}/
                %label.text.required.control-label{:for => "contact_message"}
                  %abbr{:title => "required"} *
                  Message
                %textarea#text.form-control{:cols => "40", :name => "contact[message]", :rows => "10", :type => "text"}
                  :preserve
                    
                                        %input.btn.btn-primary.btn-style{:name => "commit", :type => "submit", :value => "Send"}/
                %button.btn.btn-default.btn-style
                  %a{:href => "/"} Cancel
                  

app/views/users_admin/edit.html.erb
<div class="container">
  <div class="row"> 
    <div class="col-lg-10 ">
    <h2>Update Courses</h2>
      <h2>Update User</h2>
        <%= form_for( @user, :url => { :action => 'update' } ) do | user | %>
        <%= render( :partial => "form", :locals => { :user => user } ) %>
      <div class="form-group"> 
        <div class="col-md-8 col-md-offset-2"> 
          <%= user.submit "Save", class: "btn btn-primary", style: "margin-left: 7%"%>
          <%= link_to 'Back', users_admin_index_path, :method => 'get', :class => "btn btn-default"%>
        </div> 
      </div> 
      <% end %>
    </div>
  </div>
</div>

app/views/users_admin/edit.html.haml
.container
  .row
    .col-lg-10
      %h2 Update Courses
      %h2 Update User
      = form_for( @user, :url => { :action => 'update' } ) do | user |
        = render( :partial => "form", :locals => { :user => user } )
        .form-group
          .col-md-8.col-md-offset-2
            = user.submit "Save", class: "btn btn-primary", style: "margin-left: 7%"
            = link_to 'Back', users_admin_index_path, :method => 'get', :class => "btn btn-default"
            

app/views/users_admin/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10">
      <div class="row">
        <div class="col-md-9" id="padding">
          <div class="row">
            <div class="col-md-10">
              <p class="lead"> Listing users </p>
            </div>
            <div class="col-md-2">
              <%= link_to 'Add User', new_users_admin_path,:class => 'btn btn-primary' %>
            </div>
          </div>
          <table class="table table-striped table-hover">
            <tr>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Institution</th>
              <th>Role</th>
              <th colspan="3" class="text-center"></th>
            </tr>
                <% if @users.blank? %> 
                  <p> No Users </p>
                <% else %>
                  <% @users.each do |users| %>
                    <tr>
                      <td><%= users.first_name%></td>
                      <td><%= users.last_name%></td>
                      <td><%= users.email%></td>
                      <td><%= users.institution%></td>
                      <td><%= users.role%></td>
                      <td><%= link_to 'show',users_admin_path(users.id)%></td>
                      <td><%= link_to 'edit', edit_users_admin_path(users.id) %></td>
                      <td><%= link_to 'Destroy', users_admin_path(users.id), :method => 'delete',data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                <% end %>
          </table>
          <div  class='col-lg-offset-3'>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users_admin/index.html.haml
.container-fluid
  .row
    .col-md-10
      #padding.col-md-9
        .row
          .col-md-10
            %p.lead Listing users
          .col-md-2
            = link_to 'Add User', new_users_admin_path,:class => 'btn btn-primary'
        %table.table.table-striped.table-hover
          %tr
            %th First Name
            %th Last Name
            %th Email
            %th Institution
            %th Role
            %th.text-center{:colspan => "3"}
          - if @users.blank?
            %p No Users
          - else
            - @users.each do |users|
              %tr
                %td= users.first_name
                %td= users.last_name
                %td= users.email
                %td= users.institution
                %td= users.role
                %td= link_to 'show',users_admin_path(users.id)
                %td= link_to 'edit', edit_users_admin_path(users.id)
                %td= link_to 'Destroy', users_admin_path(users.id), :method => 'delete',data: { confirm: 'Are you sure?' }
        .col-lg-offset-3
        

app/views/users_admin/new.html.erb
<div class="container"> 
  <div class="row"> 
    <div class="col-lg-10 ">
      <h2>Create User</h2>
       <%= form_for( @user , :url => { :action => 'create' }) do | user | %>
        <%= render( :partial => "form", :locals => { :user => user } ) %>
        <div class="form-group"> 
        <div class="col-md-8 col-md-offset-2"> 
          <%= user.submit "Save", class: "btn btn-primary", style: "margin-left: 7%"%>
          <%= link_to 'Back', users_admin_index_path, :method => 'get', :class => "btn btn-default"%>
         </div> 
      </div> 
      <% end %>
    </div>
  </div>
</div>
  

app/views/users_admin/show.html.erb
<div class="container-fluid">
<div class="row">
<div class="col-md-10">
<div class="row">
<div class="col-md-9">
    <p> 
      <b>Name:</b> 
      <%= @user.last_name %>
    </p>
    <p> 
      <b>Email:</b>
      <%= @user.email %>
    </p>
    <p> 
      <b>Institution:</b>
      <%= @user.institution %>
    </p>
    <p> 
      <b>Role:</b>
      <%= @user.role %>
    </p>
    <%= link_to 'Edit', edit_users_admin_path, :class => "btn btn-success", style: "margin-left: 0%"%>
    <%= link_to 'Back', users_admin_index_path, :class => 'btn btn-default' %>  
  </div>
</div>
</div>
</div>
</div>

app/views/users_admin/show.html.haml
.container-fluid
  .row
    .col-md-10
      .row
        .col-md-9
          %p
            %b Name:
            = @user.last_name
          %p
            %b Email:
            = @user.email
          %p
            %b Institution:
            = @user.institution
          %p
            %b Role:
            = @user.role
          = link_to 'Edit', edit_users_admin_path, :class => "btn btn-success", style: "margin-left: 0%"
          = link_to 'Back', users_admin_index_path, :class => 'btn btn-default'
          