config/routes.rb
Rails.application.routes.draw do
  resources :musics

root to: 'users#index'
devise_for :users
 resources :users do 
  collection do 
    get 'sign_in'
    get 'sign_up'
    post 'valid_user'
  end
end
resources :contacts,:only => [:new,:create,:index]
match "/contacts/", :controller => 'contacts',:action => 'index' , :via => [:get, :post]
resources :courses ,:only => [:index,:new,:create,:show,:edit,:update,:destroy]
resources :gadgets,:except => :delete
resources :users_admin do
  collection do
    get 'sign_out'
    end
  end
end 

app/models/gadget.rb
class Gadget < ActiveRecord::Base
  has_and_belongs_to_many :analysis_groups 
  has_and_belongs_to_many :type_of_methods
  belongs_to :currencys
  has_and_belongs_to_many :qualify_area_of_interests
end
# class Currency < ActiveRecord::Base
#   has_one :gadgets
# end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController
#layout "gadgets"
def index
  @search = Gadget.search(params[:q])
  @gadgets = @search.result
end
def new
   @gadget = Gadget.new
end
def create
 # render :text => params.inspect and return 
  @gadget = Gadget.new(title: params[:gadget][:title],
  name_method_or_gadget: params[:gadget][:name_method_or_gadget],
  useful_for: params[:gadget][:useful_for],
  analysis_group: params[:gadget][:analysis_group],
  type_of_method_or_gadget: params[:gadget][:type_of_method_or_gadget],
  gadget_description: params[:gadget][:gadget_description],
  cost: params[:gadget][:cost],
  currencys_id: params[:gadget][:currencys_id],
  companay_name: params[:gadget][:companay_name],
  company_description: params[:gadget][:company_description],
  companay_website: params[:gadget][:companay_website],
  technology_used: params[:gadget][:technology_used],
  scientific_descrition: params[:gadget][:scientific_descrition],
  qualfiy_area_interest: params[:gadget][:qualfiy_area_interest],
  explanation_by_evaluator: params[:gadget][:explanation_by_evaluator],
  name: params[:gadget][:name],
  comments_suggestion_of_evalutor: params[:gadget][:comments_suggestion_of_evalutor])
   analysys_array = params[:gadget][:analysis_group]
   # render :text => analysys_array.inspect and return
     if !analysys_array.nil?   
     # render :text => analysys_array.inspect and return
       analysys_array.each do |f| 
        @gadget.analysis_groups << AnalysisGroup.find_by_id(f.to_i)
       end
     end
  type_of_method_or_gadget_array = params[:gadget][:type_of_method_or_gadget]
    if !type_of_method_or_gadget_array.nil?   
      type_of_method_or_gadget_array.each do |t| 
        #render :text => f.select(:name).inspect and return
        @gadget.type_of_methods <<  TypeOfMethod.find(t.to_i)
      end
    end
  qualfiy_area_interest_array = params[:gadget][:qualfiy_area_interest]
    if !qualfiy_area_interest_array.nil?   
      qualfiy_area_interest_array.each do |p| 
        @gadget.qualify_area_of_interests <<  QualifyAreaOfInterest.find(p.to_i)
      end
    end
  if @gadget.save
    flash[:notice] =  'Gadget successfully created.' 
    redirect_to gadgets_path
  else
    flash[:error] =  'Problem creating Gadget.' 
    render 'new'
  end
end
def show
  @gadget = Gadget.find(params[:id])
end
def edit
  @gadget = Gadget.find(params[:id])
  if !@gadget.nil?
    render 'edit'
  else
    render 'index'
  end
end
def update
    @gadget = Gadget.find(params[:id])
    @gadget.title = params[:gadget][:title]
    @gadget.companay_name = params[:gadget][:companay_name]
    @gadget.name_method_or_gadget = params[:gadget][:name_method_or_gadget]
    @gadget.useful_for = params[:gadget][:useful_for]
    @gadget.gadget_description = params[:gadget][:gadget_description]
    @gadget.cost = params[:gadget][:cost]
    @gadget.company_description = params[:gadget][:company_description]
    @gadget.companay_website = params[:gadget][:companay_website]
    if @gadget.save
      redirect_to gadgets_path
    else
      render 'edit'
    end
end
def destroy
  @gadget = Gadget.find(params[:id]).destroy
  redirect_to  gadgets_path
end
end

app/helpers/gadgets_helper.rb
module GadgetsHelper
end

app/views/gadgets/_form.html.erb
<div class="container">
  <div class="col-lg-10">
    <div class="row">
      <div class="form-group">      
        <div class="col-md-9">
          <%= gadget.text_field :title, required: true, class: 'form-control input-md', placeholder: 'Enter Title Here' %>
        </div>
        <div class="col-md-3"> 
          <%= link_to "Back", gadgets_path, class: 'btn btn-primary' %>
          <%= gadget.submit "Save", class: 'btn btn-primary' %>
        </div>
      </div>
    </div><hr/>
    <div class="col-lg-8">
      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Name of the method/gadget</label>  
            <div class="col-md-7">
              <%= gadget.text_field :name_method_or_gadget, required: true, class: 'form-control input-md' %>
            </div>
        </div>
      </div><br>
      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">What is it for?</label>  
            <div class="col-md-7">
              <%= gadget.text_field :useful_for, class: 'form-control input-md' %>
            </div>
        </div>
      </div><br>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Analysis group(s)</label>
            <div class="col-md-7" style="padding-top:13px">
              <% AnalysisGroup.all.each do |a_value| %> 
                
                <% if @gadget.new_record? %>&nbsp
                  <%= gadget.check_box(:analysis_group, { :multiple => true }, a_value.id, nil) %>
                  <%=  a_value.name %>
                <% else %>
                    <% if @gadget.analysis_groups.pluck(:id).include?(a_value.id)  %>
                    <%= gadget.check_box(:analysis_group, { :multiple => true, checked:  true}, a_value.id, nil) %>
                      <%=  a_value.name %>  
                      
                    <% else %>
                      <%= gadget.check_box(:analysis_group, { :multiple => true }, a_value.id, nil) %>
                      <%=  a_value.name %>  
                    <% end %> 
                <% end %>
              <% end %>
            </div>
        </div>
      </div><br>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Type of method/gadget</label>
            <div class="col-md-7" style="padding-top:13px">
              <% TypeOfMethod.all.each do |a_value| %> 
                <% if @gadget.new_record? %>
                  <%= gadget.check_box(:type_of_method_or_gadget , { :multiple => true }, a_value.id, nil) %>
                  <%=  a_value.name %>  
                <% else %>
                  <% if @gadget.type_of_methods.pluck(:id).include?(a_value.id)   %>
                    <%= gadget.check_box(:type_of_method_or_gadget , { :multiple => true, checked:  true}, a_value.id, nil) %>
                    <%=  a_value.name %>  
                  <% else %>
                    <%= gadget.check_box(:type_of_method_or_gadget , { :multiple => true }, a_value.id, nil) %>
                    <%=  a_value.name %>  
                  <% end %> 
                <% end %>
              <% end %>
            </div>
        </div>
      </div><br>
        
      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label" for="">Gadget Description</label>
            <div class="col-md-7"> 
              <%= gadget.text_area :gadget_description, class: 'form-control', rows: 4 %>
            </div>
        </div>
      </div><br>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label" for="buttondropdown">Cost</label>
            <div class="col-md-5">
              <%= gadget.text_field :cost, class: 'form-control' %>
            </div>
            <div class="col-md-3">
              <%= gadget.select :currencys_id, Currency.all.collect {|p| [ p.name, p.id] },{:default => 'Guest'}, {:class => 'form-control', id: 'currency_select'} %>
            </div>  
        </div>
      </div><br>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Company name</label>  
            <div class="col-md-7">
              <%= gadget.text_field :companay_name, class: 'form-control input-md' %>
            </div>
        </div>
      </div><br>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Company description</label>  
            <div class="col-md-7">
              <%= gadget.text_area :company_description, class: 'form-control input-md', rows:4 %>
            </div>
        </div>
      </div><br>
        
      <div class="row">     
        <div class="form-group">
          <label class="col-md-4 control-label">Company website</label>  
            <div class="col-md-7">
              <%= gadget.text_field :companay_website, class: 'form-control input-md' %>
            </div>
        </div>
      </div><br>
        
      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Technology used</label>  
            <div class="col-md-7">
              <%= gadget.text_field :technology_used, class: 'form-control input-md' %>
            </div>
        </div>
      </div><br>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Scientific description of</label>  
            <div class="col-md-7">
              <%= gadget.text_area :scientific_descrition, class: 'form-control input-md', rows: 4 %>
            </div>
        </div>
      </div><br>

      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">QuaLiFY area of interest</label>
            <div class="col-md-7" style="padding-top:13px">
              <% QualifyAreaOfInterest.all.each do |a_value| %> 
                <% if @gadget.new_record? %>
                  <%= gadget.check_box(:qualfiy_area_interest, { :multiple => true }, a_value.id, nil) %>
                  <%=  a_value.name %>  
                  <% else %>
                    <% if @gadget.qualify_area_of_interests.pluck(:id).include?(a_value.id)   %>
                      <%= gadget.check_box(:qualfiy_area_interest, { :multiple => true, checked:  true}, a_value.id, nil) %>
                      <%=  a_value.name %>  
                    <% else %>
                      <%= gadget.check_box(:qualfiy_area_interest, { :multiple => true }, a_value.id, nil) %>
                      <%=  a_value.name %>  
                  <% end %> 
                <% end %>
              <% end %>
            </div>
        </div>
      </div><br>
        
      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Explanation by evaluator(NRC)</label>
            <div class="col-md-7"> 
              <%= gadget.text_area :explanation_by_evaluator, class: 'form-control input-md', rows: 4 %>
            </div>
        </div>
      </div><br><hr/>
        
      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Name of evaluator(NRC)</label>  
            <div class="col-md-7">
              <%= gadget.text_field :name, class: 'form-control input-md',
                   id: 'fieldwidth' %>
            </div>
        </div>
      </div><br>
        
      <div class="row">
        <div class="form-group">
          <label class="col-md-4 control-label">Comments/suggestion of evaluator</label>  
            <div class="col-md-7">
              <%= gadget.text_area :comments_suggestion_of_evalutor, class: 'form-control input-md', rows: 4, id: 'fieldwidth' %>
            </div>
        </div>  
      </div><br>
    </div>
  </div> 
</div>
  
 

    

app/views/gadgets/_form.html.haml
.container
  .col-lg-10.col-lg-push-5
    .row
      .form-group
        .col-md-9
          = gadget.text_field :title, required: true, class: 'form-control input-md', placeholder: 'Enter Title Here'
        .col-md-3
          = link_to "Back", gadgets_path, class: 'btn btn-primary'
          = gadget.submit "Save", class: 'btn btn-primary'
    %hr/
    .col-lg-8
      .row
        .form-group
          %label.col-md-4.control-label Name of the method/gadget
          .col-md-7
            = gadget.text_field :name_method_or_gadget, required: true, class: 'form-control input-md'
      %br
        .row
          .form-group
            %label.col-md-4.control-label What is it for?
            .col-md-7
              = gadget.text_field :useful_for, class: 'form-control input-md'
        %br
          .row
            .form-group
              %label.col-md-4.control-label Analysis group(s)
              .col-md-7{:style => "padding-top:13px"}
                - AnalysisGroup.all.each do |a_value|
                  - if @gadget.new_record?
                    \&nbsp
                    \#{gadget.check_box(:analysis_group, { :multiple => true }, a_value.id, nil)}
                    \#{a_value.name}
                  - else
                    - if @gadget.analysis_groups.pluck(:id).include?(a_value.id)
                      = gadget.check_box(:analysis_group, { :multiple => true, checked:  true}, a_value.id, nil)
                      = a_value.name
                    - else
                      = gadget.check_box(:analysis_group, { :multiple => true }, a_value.id, nil)
                      = a_value.name
          %br
            .row
              .form-group
                %label.col-md-4.control-label Type of method/gadget
                .col-md-7{:style => "padding-top:13px"}
                  - TypeOfMethod.all.each do |a_value|
                    - if @gadget.new_record?
                      = gadget.check_box(:type_of_method_or_gadget , { :multiple => true }, a_value.id, nil)
                      = a_value.name
                    - else
                      - if @gadget.type_of_methods.pluck(:id).include?(a_value.id)
                        = gadget.check_box(:type_of_method_or_gadget , { :multiple => true, checked:  true}, a_value.id, nil)
                        = a_value.name
                      - else
                        = gadget.check_box(:type_of_method_or_gadget , { :multiple => true }, a_value.id, nil)
                        = a_value.name
            %br
              .row
                .form-group
                  %label.col-md-4.control-label{:for => ""} Gadget Description
                  .col-md-7
                    = gadget.text_area :gadget_description, class: 'form-control', rows: 4
              %br
                .row
                  .form-group
                    %label.col-md-4.control-label{:for => "buttondropdown"} Cost
                    .col-md-5
                      = gadget.text_field :cost, class: 'form-control'
                    .col-md-3
                      = gadget.select :currencys_id, Currency.all.collect {|p| [ p.name, p.id] },{:default => 'Guest'}, {:class => 'form-control', id: 'currency_select'}
                %br
                  .row
                    .form-group
                      %label.col-md-4.control-label Company name
                      .col-md-7
                        = gadget.text_field :companay_name, class: 'form-control input-md'
                  %br
                    .row
                      .form-group
                        %label.col-md-4.control-label Company description
                        .col-md-7
                          = gadget.text_area :company_description, class: 'form-control input-md', rows:4
                    %br
                      .row
                        .form-group
                          %label.col-md-4.control-label Company website
                          .col-md-7
                            = gadget.text_field :companay_website, class: 'form-control input-md'
                      %br
                        .row
                          .form-group
                            %label.col-md-4.control-label Technology used
                            .col-md-7
                              = gadget.text_field :technology_used, class: 'form-control input-md'
                        %br
                          .row
                            .form-group
                              %label.col-md-4.control-label Scientific description of
                              .col-md-7
                                = gadget.text_area :scientific_descrition, class: 'form-control input-md', rows: 4
                          %br
                            .row
                              .form-group
                                %label.col-md-4.control-label QuaLiFY area of interest
                                .col-md-7{:style => "padding-top:13px"}
                                  - QualifyAreaOfInterest.all.each do |a_value|
                                    - if @gadget.new_record?
                                      = gadget.check_box(:qualfiy_area_interest, { :multiple => true }, a_value.id, nil)
                                      = a_value.name
                                    - else
                                      - if @gadget.qualify_area_of_interests.pluck(:id).include?(a_value.id)
                                        = gadget.check_box(:qualfiy_area_interest, { :multiple => true, checked:  true}, a_value.id, nil)
                                        = a_value.name
                                      - else
                                        = gadget.check_box(:qualfiy_area_interest, { :multiple => true }, a_value.id, nil)
                                        = a_value.name
                            %br
                              .row
                                .form-group
                                  %label.col-md-4.control-label Explanation by evaluator(NRC)
                                  .col-md-7
                                    = gadget.text_area :explanation_by_evaluator, class: 'form-control input-md', rows: 4
                              %br
                                %hr/
                                .row
                                  .form-group
                                    %label.col-md-4.control-label Name of evaluator(NRC)
                                    .col-md-7
                                      = gadget.text_field :name, class: 'form-control input-md', |
                                        id: 'fieldwidth'                                         |
                                %br
                                  .row
                                    .form-group
                                      %label.col-md-4.control-label Comments/suggestion of evaluator
                                      .col-md-7
                                        = gadget.text_area :comments_suggestion_of_evalutor, class: 'form-control input-md', rows: 4, id: 'fieldwidth'
                                  %br
                                  

app/views/gadgets/_search.html.erb
<div class="col-md-8 col-xs-5 col-md-offset-0">
  <div class="thumbnail">
    <div class="caption">
      <form class="form-horizontal">
        <fieldset>
          <legend>Gadget Inventory</legend>
            <div class="form-group">
              <%= search_form_for @search do | f | %>
                <div class="col-md-5">
                  <label><%= f.label :title_start, "Search by: Gadget title" %></label>
                    <%= f.text_field :title_start %><br/><br/>
                  <label><%= f.label :analysis_group, "Search by:Analysis Group" %></label>
                    <%= f.text_field :analysis_group_start %></br><br/>
                    <%= f.submit "Search", :class => "btn btn-default" %>
                </div>
              <% end %>
            </div>
        </fieldset>
      </form>
    </div>
  </div>
</div>

app/views/gadgets/_search.html.haml
.col-md-6.col-md-pull-7
  %p.alert
  .col-md-8.col-xs-5.col-md-push-2
    .thumbnail
      .caption
        %form.form-horizontal
          %fieldset
            %legend Gadget Inventory
            .form-group
              = search_form_for @search do | f |
                .col-md-5
                  %label= f.label :title_start, "Search by: Gadget title"
                  = f.text_field :title_start
                  %br/
                  %br/
                  %label= f.label :analysis_group, "Search by:Analysis Group"
                  = f.text_field :analysis_group_start
                  %br/
                  = f.submit "Search", :class => "btn btn-default"
                  

app/views/gadgets/edit.html.erb
<div class="container">
  <div class="row"> 
    <div class="col-lg-10 ">
      <h2>Update Gadget</h2>
        <%= form_for( @gadget, :url => { :action => 'update' }) do | gadget | %>
        <%= render( :partial => "form", :locals => { :gadget => gadget } ) %>
      <div class="form-group"> 
        <div class="col-md-8 col-md-offset-2"> 
          <%= gadget.submit "Update Gadget", class: "btn btn-primary", style: "margin-left: 7%" %>
          <%= link_to 'Back', gadgets_path, :method => 'get', :class => "btn btn-default" %>
         </div> 
      </div> 
      <% end %>
    </div>
  </div>
</div>

app/views/gadgets/edit.html.haml
.container
  .row
    .col-lg-10
      %h2 Update Gadget
      = form_for( @gadget, :url => { :action => 'update' }) do | gadget |
        = render( :partial => "form", :locals => { :gadget => gadget } )
        .form-group
          .col-md-8.col-md-offset-2
            = gadget.submit "Update Gadget", class: "btn btn-primary", style: "margin-left: 7%"
            = link_to 'Back', gadgets_path, :method => 'get', :class => "btn btn-default"
            

app/views/gadgets/index.html.erb
<%= render 'search' %>
<div class="row">
  <div class="col-md-10" id="padding">
    <div class="col-md-10">
      <p class="lead"> Gadget Inventory</p> 
      <div class="row">
        </br>
      </div>
    </div>
    <div class="col-md-2">
      <%= link_to 'ADD GADGET', new_gadget_path, class: 'btn btn-primary' %>
    </div>
    <% if !@gadgets.empty? %>
      <table class="table table-striped table-hover">
          <tr>
             <th><%= sort_link @search, :title, "Gadget Title" %></th>
            <th><%= sort_link @search, :name_method_or_gadget, "Name of the tool" %></th>
            <th>Analysis Group(s)</th>
            <th>Actions</th>
            <th colspan="3" class="text-center"></th>
          </tr>
        <% @gadgets.each do | gadget | %>
          <tr>
            <td><%= gadget.title %></td>
            <td><%= gadget.name_method_or_gadget %></td>
            <td><% gadget.analysis_groups.each do |temp| %>
                <% if temp == gadget.analysis_groups.last %>
                  <%= temp.name%>
                <% else%>
                  <%= temp.name+","%>
                <% end %>
                <% end %>
            </td>
            <td><%= link_to 'Show', gadget_path(gadget.id) %></td>
            <td><%= link_to 'Edit', edit_gadget_path(gadget.id) %></td>
            <td><%= link_to 'Delete',gadget_path(gadget.id), :method => 'delete' %></td>
          </tr>
        <% end %>
      </table>
    <% else %>
      <div class="col-md-10">
        <p class="text-center"> There are no matched records.</p>
      </div>
    <% end %>
  </div>
</div>

app/views/gadgets/index.html.haml
= render 'search'
.row
  #padding.col-md-10
    .col-md-10
      %p.lead Gadget Inventory
      .row
    .col-md-2.col-push-1
      = link_to 'ADD GADGET', new_gadget_path, class: 'btn btn-primary'
    .col-md-12.col-md-push-1.col-md-offset-3
    - if !@gadgets.empty?
      %table.table.table-striped.table-hover
        %tr
          %th= sort_link @search, :title, "Gadget Title"
          %th= sort_link @search, :name_method_or_gadget, "Name of the tool"
          %th Analysis Group(s)
          %th Actions
          %th.text-center{:colspan => "3"}
        - @gadgets.each do | gadget |
          %tr
            %td= gadget.title
            %td= gadget.name_method_or_gadget
            %td
              - gadget.analysis_groups.each do |temp|
                - if temp == gadget.analysis_groups.last
                  = temp.name
                - else
                  = temp.name+","
            %td= link_to 'Show', gadget_path(gadget.id)
            %td= link_to 'Edit', edit_gadget_path(gadget.id)
            %td= link_to 'Delete',gadget_path(gadget.id), :method => 'delete'
    - else
      .col-md-10
        %p.text-center There are no matched records.
        

app/views/gadgets/new.html.erb
<div class="container">
  <div class="row"> 
    <div class="col-lg-10 ">              
      <h2>Create Gadget</h2>
      <%= form_for(@gadget,:url => { :action => 'create',:method =>'post'}) do | gadget | %>
      <%= render( :partial => "form", :locals => { :gadget => gadget } ) %>
      <div class="form-group"> 
        <div class="col-md-8 col-md-offset-2"> 
         <div class="text-center"> 
        <%= link_to "Back", gadgets_path, class: 'btn btn-primary' %>
        <%= gadget.submit "Save", class: 'btn btn-primary' %>
        </div>
        </div> 
      </div> 
      <% end %>
    </div>
  </div>   
</div>

app/views/gadgets/new.html.haml
.container
  .row
    .col-lg-10
      %h2 Create Gadget
      = form_for(@gadget,:url => { :action => 'create',:method =>'post'}) do | gadget |
        = render( :partial => "form", :locals => { :gadget => gadget } )
        .form-group
          .col-md-8.col-md-offset-2
            .text-center
              = link_to "Back", gadgets_path, class: 'btn btn-primary'
              = gadget.submit "Save", class: 'btn btn-primary'
              

app/views/gadgets/show.html.erb
<div class="row">
  <div class="form-group">
    <div class="col-md-5">Gadget</div>
    <div class="col-md-7">
      <%= link_to 'Back', gadgets_path,:class => 'btn btn-primary' %> 
      <%= link_to 'Edit', edit_gadget_path,:class => "btn btn-primary" %>
    </div>
  </div>
</div> 
<hr/>

<div class="row">
  <div class="col-md-8">
    <dl>
      <dt>Name of the method/gadget</dt>
      <dd><%= @gadget.name_method_or_gadget %></dd>
    </dl>

    <dl>
      <dt>What is it for?</dt>
      <dd><%= @gadget.useful_for %></dd>
    </dl>
            
    <dl>
      <% if !@gadget.analysis_group.empty? %>
        <dt>Analysis group(s)</dt>
          <% @gadget.analysis_groups.each do |group| %>
            <dd> <%= group.name %></dd>
          <% end %>
      <% end %>
    </dl>
 
    <dl>
      <dt>Type of method/gadget</dt>
      <% if !@gadget.type_of_method_or_gadget.empty? %>
          <% @gadget.type_of_methods.each do |group| %>
            <dd> <%= group.name %></dd>
          <% end %>
      <% end %>
    </dl> 
            
    <dl>
      <dt>Gadget description</dt>
      <dd><%= @gadget.gadget_description %></dd>
    </dl>
            
     <dl>
        <% if !@gadget.cost.nil?%>
          <dt>Cost</dt>
          <dd> <%= @gadget.cost %></dd>
        <% end %>
    </dl>
  </div>
</div>
<hr/>
  
  <dl>
    <dt>Company name</dt>
    <dd> <%= @gadget.companay_name%></dd>
  </dl>
        
  <dl>
    <dt>Company description</dt>
    <dd><%= @gadget.company_description%></dd>
  </dl>
        
  <dl>
    <dt>Company website</dt>
    <dd> <%= @gadget.companay_website%></dd>
  </dl>

 
    
  <dl>
    <dt>Evaluated by NRC </dt>
    <dd><%if  @gadget.explanation_by_evaluator %>
              Yes
        <% else %>
              No
        <% end %>
    </dd>
  </dl>

  <dl>
    <dt>Name of evaluator </dt>
      <dd>
        <%if  @gadget.name %>
              Yes
        <% else %>
              No
        <% end %>
      </dd>
  </dl>
        
  <dl>
    <dt>Usefulness for which field lab? </dt>
    <dd><%if  @gadget.useful_which_field_lab %>
              Yes
        <% else %>
              No
        <% end %> </dd>
  </dl>
</div>

app/views/gadgets/show.html.haml
.row
  .form-group
    .col-md-5 Gadget
    .col-md-7
      = link_to 'Back', gadgets_path,:class => 'btn btn-primary'
      = link_to 'Edit', edit_gadget_path,:class => "btn btn-primary"
%hr/
.row
  .col-md-8
    %dl
      %dt Name of the method/gadget
      %dd= @gadget.name_method_or_gadget
    %dl
      %dt What is it for?
      %dd= @gadget.useful_for
    %dl
      - if !@gadget.analysis_group.empty?
        %dt Analysis group(s)
        - @gadget.analysis_groups.each do |group|
          %dd
            = group.name
    %dl
      %dt Type of method/gadget
      - if !@gadget.type_of_method_or_gadget.empty?
        - @gadget.type_of_methods.each do |group|
          %dd
            = group.name
    %dl
      %dt Gadget description
      %dd= @gadget.gadget_description
    %dl
      - if !@gadget.cost.nil?
        %dt Cost
        %dd
          = @gadget.cost
%hr/
%dl
  %dt Company name
  %dd
    = @gadget.companay_name
%dl
  %dt Company description
  %dd= @gadget.company_description
%dl
  %dt Company website
  %dd
    = @gadget.companay_website
%dl
  %dt Evaluated by NRC
  %dd
    - if  @gadget.explanation_by_evaluator
      Yes
    - else
      No
%dl
  %dt Name of evaluator
  %dd
    - if  @gadget.name
      Yes
    - else
      No
%dl
  %dt Usefulness for which field lab?
  %dd
    - if  @gadget.useful_which_field_lab
      Yes
    - else
      No
      