config/routes.rb
Rails.application.routes.draw do
  resources :musics

root to: 'users#index'
devise_for :users
 resources :users do 
  collection do 
    get 'sign_in'
    get 'sign_up'
    post 'valid_user'
  end
end
resources :contacts,:only => [:new,:create,:index]
match "/contacts/", :controller => 'contacts',:action => 'index' , :via => [:get, :post]
resources :courses ,:only => [:index,:new,:create,:show,:edit,:update,:destroy]
resources :gadgets,:except => :delete
resources :users_admin do
  collection do
    get 'sign_out'
    end
  end
end 

app/models/music.rb
class Music < ActiveRecord::Base
has_attached_file :image, :styles => {:small => "100*100"}
validates_attachment_presence :image
validates_attachment_content_type :image, :content_type => [ 'image/png','image/jpeg','image/jpeg']
has_attached_file :document
validates_attachment_presence :document
validates_attachment_content_type :document, :content_type => [ 'application/pdf','text/plain']
has_attached_file :audio
validates_attachment_presence :audio
validates_attachment_content_type :audio, :content_type => [ 'audio/mp3','audio/mpeg']
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show, :edit, :update, :destroy]
  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all
  end
  # GET /musics/1
  # GET /musics/1.json
  def show
  end
  # GET /musics/new
  def new
    @music = Music.new
  end
  # GET /musics/1/edit
  def edit
  end
  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(music_params)
    respond_to do |format|
      if @music.save
        format.html { redirect_to @music, notice: 'Music was successfully created.' }
        format.json { render :show, status: :created, location: @music }
      else
        format.html { render :new }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /musics/1
  # PATCH/PUT /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to @music, notice: 'Music was successfully updated.' }
        format.json { render :show, status: :ok, location: @music }
      else
        format.html { render :edit }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url, notice: 'Music was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def music_params
      params.require(:music).permit(:image, :document, :audio)
    end
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/musics/_form.html.erb
<%= f.file_field :image %>
<%= f.file_field :document %>
<%= f.file_field :audio %>


<%= form_for(@music) do |f| %>
  <% if @music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% @music.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :document %><br>
    <%= f.text_field :document %>
  </div>
  <div class="field">
    <%= f.label :audio %><br>
    <%= f.text_field :audio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musics/_form.html.haml
= f.file_field :image
= f.file_field :document
= f.file_field :audio
= form_for(@music) do |f|
  - if @music.errors.any?
    #error_explanation
      %h2
        = pluralize(@music.errors.count, "error")
        prohibited this music from being saved:
      %ul
        - @music.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :image
    %br/
    = f.text_field :image
  .field
    = f.label :document
    %br/
    = f.text_field :document
  .field
    = f.label :audio
    %br/
    = f.text_field :audio
  .actions
    = f.submit
    

app/views/musics/edit.html.erb
<h1>Editing music</h1>

<%= render 'form' %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/edit.html.haml
%h1 Editing music
= render 'form'
= link_to 'Show', @music
|
\#{link_to 'Back', musics_path}

app/views/musics/index.html.erb
<h1>Listing musics</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Document</th>
      <th>Audio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @musics.each do |music| %>
      <tr>
        <td><%= music.image %></td>
        <td><%= music.document %></td>
        <td><%= music.audio %></td>
        <td><%= link_to 'Show', music %></td>
        <td><%= link_to 'Edit', edit_music_path(music) %></td>
        <td><%= link_to 'Destroy', music, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Music', new_music_path %>

<td>
<%= image_tag(order.image.url(:small)) %>   
<%= order.document_file_name %>
<%= order.audio_file_name %></td>

app/views/musics/index.html.haml
%h1 Listing musics
%table
  %thead
    %tr
      %th Image
      %th Document
      %th Audio
      %th{colspan: "3"}
  %tbody
    - @musics.each do |music|
      %tr
        %td= music.image
        %td= music.document
        %td= music.audio
        %td= link_to 'Show', music
        %td= link_to 'Edit', edit_music_path(music)
        %td= link_to 'Destroy', music, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Music', new_music_path
%td
  = image_tag(order.image.url(:small))
  = order.document_file_name
  = order.audio_file_name
  

app/views/musics/new.html.erb
<h1>New music</h1>

<%= render 'form' %>

<%= link_to 'Back', musics_path %>

app/views/musics/new.html.haml
%h1 New music
= render 'form'
= link_to 'Back', musics_path

app/views/musics/show.html.erb
<b>Image:</b>
<%= image_tag(@order.image.url(:small)) %>
<b>Document:</b>
<%= @order.document_file_name %>
<b>Audio:</b>
<%= @order.audio_file_name %>


<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @music.image %>
</p>

<p>
  <strong>Document:</strong>
  <%= @music.document %>
</p>

<p>
  <strong>Audio:</strong>
  <%= @music.audio %>
</p>

<%= link_to 'Edit', edit_music_path(@music) %> |
<%= link_to 'Back', musics_path %>

app/views/musics/show.html.haml
%b Image:
= image_tag(@order.image.url(:small))
%b Document:
= @order.document_file_name
%b Audio:
= @order.audio_file_name
%p#notice= notice
%p
  %strong Image:
  = @music.image
%p
  %strong Document:
  = @music.document
%p
  %strong Audio:
  = @music.audio
= link_to 'Edit', edit_music_path(@music)
|
\#{link_to 'Back', musics_path}