config/routes.rb
Rails.application.routes.draw do
  resources :musics

root to: 'users#index'
devise_for :users
 resources :users do 
  collection do 
    get 'sign_in'
    get 'sign_up'
    post 'valid_user'
  end
end
resources :contacts,:only => [:new,:create,:index]
match "/contacts/", :controller => 'contacts',:action => 'index' , :via => [:get, :post]
resources :courses ,:only => [:index,:new,:create,:show,:edit,:update,:destroy]
resources :gadgets,:except => :delete
resources :users_admin do
  collection do
    get 'sign_out'
    end
  end
end 

app/models/analysis_group.rb
class AnalysisGroup < ActiveRecord::Base
  has_and_belongs_to_many :gadgets
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/contacts.rb
class Contacts < ActiveRecord::Base
end

app/models/course.rb
class Course < ActiveRecord::Base
  # has_and_belongs_to_many :gadgets
end

app/models/currencies.rb
class Currencies < ActiveRecord::Base
  has_one :gadgets
end

app/models/currency.rb
class Currency < ActiveRecord::Base

 has_one :gadgets

end

app/models/gadget.rb
class Gadget < ActiveRecord::Base
  has_and_belongs_to_many :analysis_groups 
  has_and_belongs_to_many :type_of_methods
  belongs_to :currencys
  has_and_belongs_to_many :qualify_area_of_interests
end
# class Currency < ActiveRecord::Base
#   has_one :gadgets
# end

app/models/gadgets_qua_area_ints.rb
class GadgetsQuaAreaInts < ActiveRecord::Base
end

app/models/idea.rb
class Idea < ActiveRecord::Base
mount_uploader :picture, PictureUploader
end

app/models/music.rb
class Music < ActiveRecord::Base
has_attached_file :image, :styles => {:small => "100*100"}
validates_attachment_presence :image
validates_attachment_content_type :image, :content_type => [ 'image/png','image/jpeg','image/jpeg']
has_attached_file :document
validates_attachment_presence :document
validates_attachment_content_type :document, :content_type => [ 'application/pdf','text/plain']
has_attached_file :audio
validates_attachment_presence :audio
validates_attachment_content_type :audio, :content_type => [ 'audio/mp3','audio/mpeg']
end

app/models/type_of_method.rb
class TypeOfMethod < ActiveRecord::Base
  has_and_belongs_to_many :gadgets
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email,:password, presence: true
  def _user
    @_user = current_user.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 # protect_from_forgery with: :exception
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show, :edit, :update, :destroy]
  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all
  end
  # GET /musics/1
  # GET /musics/1.json
  def show
  end
  # GET /musics/new
  def new
    @music = Music.new
  end
  # GET /musics/1/edit
  def edit
  end
  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(music_params)
    respond_to do |format|
      if @music.save
        format.html { redirect_to @music, notice: 'Music was successfully created.' }
        format.json { render :show, status: :created, location: @music }
      else
        format.html { render :new }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /musics/1
  # PATCH/PUT /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to @music, notice: 'Music was successfully updated.' }
        format.json { render :show, status: :ok, location: @music }
      else
        format.html { render :edit }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url, notice: 'Music was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def music_params
      params.require(:music).permit(:image, :document, :audio)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @list = User.all
  end
  def create
    @user = User.new
    @user.first_name = params[:user][:first_name]
    @user.last_name = params[:user][:last_name]
    @user.institution = params[:user][:institution]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    if
      @user.save
      redirect_to users_admin_index_path
      flash[:notice] = "You are signed up successfully"
    end
  end
  # def show
  #   @user = User.find(params[:id])
    
  # end
  def new
     render sign_up_users_path
  end
  def update
  end
  def valid_user
    @temp_email = params[:user][:email]
    @temp_password = params[:user][:password]
    @check_email = User.find_by_email(@temp_email)
    @check_password = User.find_by_password(@temp_password)
    if @check_email.nil? or @check_password.nil?
      flash[:notice] = "Entered Email-Id/Password is Invalid"
      redirect_to sign_in_users_path
    else
      redirect_to users_admin_index_path
    end
  end
  def sign_in
  end
  def sign_up
  end
  def sign_out
     @user.email = nil
     @user.password = nil
     render :text => params.inspect and return 
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/gadgets_helper.rb
module GadgetsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/usres_helper.rb
module UsresHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="nav navbar-header">
    <a href="/contacts/new" class="navbar-brand">Contact</a>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li id="test2" class="dropdown">
        <a href="#" class="dropdown" data-toggle="dropdown">
        <h5>Produts<span class="caret"></span></h5>
        </a>
        <ul id="test3" class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
          <li><a  href="http://navaratan.com/home/aboutus"><h5>About Us</h5></a></li>
          <li><a  href="http://navaratan.com/home/services"><h5>Services</h5></a></li>
          <li><a  href="http://navaratan.com/home/careers"><h5>Careers</h5></a></li>
        </ul>
      </li>
    </ul>
    <div class="nav navbar-nav pull-right">
    <% if user_signed_in? %>
      <ul>
      Logged in as <strong><%= current_user.email %></strong>
      <%= link_to 'Edit profile', edit_user_registration_path %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
      <%= link_to "Sign up", new_user_registration_path %>
      <%= link_to "Login", new_user_session_path %>
      </ul>
    <% end %>
    </div>
  </div>
</nav><hr/>

app/views/application/_navbar.html.haml
%nav.navbar.navbar-inverse{:role => "navigation"}
  .nav.navbar-header
    %a.navbar-brand{:href => "contactsnew"} Contact
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    %ul.nav.navbar-nav
      %li#test2.dropdown
        %a.dropdown{"data-toggle" => "dropdown", :href => "#"}
          %h5
            Produts
            %span.caret
        %ul#test3.dropdown-menu{"aria-labelledby" => "dropdownMenu", :role => "menu"}
          %li
            %a{:href => "about.html"}
              %h5 About Us
          %li
            %a{:href => "service.html"}
              %h5 Management Team
          %li
            %a{:href => "#"}
              %h5 Careers
    .nav.navbar-nav.pull-right
      - if user_signed_in?
        %ul
          Logged in as
          %strong= current_user.email
          = link_to 'Edit profile', edit_user_registration_path
          = link_to "Logout", destroy_user_session_path, method: :delete
      - else
        = link_to "Sign up", new_user_registration_path
        = link_to "Login", new_user_session_path
%hr

  

app/views/application/_sidebar.html.erb
<% if user_signed_in? %>

<div class="sidebar-padding">
<center><h4>Our Service</h4></center>
	<div class="list-group">
        <%= link_to 'Users', users_admin_index_path, :method => 'get', :class => "list-group-item"%>
        <%= link_to 'Courses', courses_path, :method => 'get', :class => "list-group-item"%>
        <%= link_to 'Gadgets Inventory', gadgets_path, :method =>'get', :class => "list-group-item"%><br/><hr>
        
        <!--<%#= link_to 'Logged in',users_path,:method => 'get',:class => "list-group-item active"%> -->
        <h4>
        <ul class="nav nav-pills nav-stacked">
          <li><center><strong><u><a href="/users/"><%= current_user.email %></a></u></strong></center></li>
          <li class="active"><a href="#">COMPOSE</a></li>
          <li><a href="#">Inbox</a></li>
          <li><a href="#">Starred</a></li>
          <li><a href="#">Important</a></li>
          <li><a href="#">Sent Mail</a></li>
          <li><a href="#">Drafts</a></li>
        </ul>
        </h4>
  </div>
<% else %>
<div> hai</div>
<% end %>

app/views/application/_sidebar.html.haml
%div
  .row
    .col
      .col-md-9
        - if user_signed_in?
          .sidebar-padding
            %center
              %h4 Our Service
            .list-group
              = link_to 'Users', users_admin_index_path, :method => 'get', :class => "list-group-item"
              = link_to 'Courses', courses_path, :method => 'get', :class => "list-group-item"
              = link_to 'Gadgets Inventory', gadgets_path, :method =>'get', :class => "list-group-item"
              %br/
              %hr
                / </haml:block><haml:silent></haml:silent><haml:block>
                %h4
                  %ul.nav.nav-pills.nav-stacked
                    %li
                      %center
                        %strong
                          %u
                            %a{:href => "/users/"}= current_user.email
                    %li.active
                      %a{:href => "#"} COMPOSE
                    %li
                      %a{:href => "#"} Inbox
                    %li
                      %a{:href => "#"} Starred
                    %li
                      %a{:href => "#"} Important
                    %li
                      %a{:href => "#"} Sent Mail
                    %li
                      %a{:href => "#"} Drafts
        - else
          %div hai
%div